package:
  name: lab_config
  version: {{ environ.get('GIT_DESCRIBE_TAG', '')[1:] }}{{ '+' + environ.get('GIT_DESCRIBE_NUMBER', '0') + '.' + environ.get('GIT_DESCRIBE_HASH', '0') if environ.get('GIT_DESCRIBE_NUMBER', '0') != '0' else "" }}

source:
  git_url: ..
  git_tag: HEAD

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python
    - pyside

test:
  imports:
    - config

about:
  home: https://github.com/DudLab/lab_config
  license: BSD???
  summary: A package of utilities in use in our lab.
